set -g mouse on
setw -g mode-keys vi

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Automatically restore the last saved environment when tmux starts
set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'   # restore what was on screen
set -g @resurrect-processes 'default'          # restart programs that were running (vim, etc.)

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
